### ISSUE TITLE
Error on sudo make

### ISSUE THREAD

**Issue by The-Shivam-tech** [keralahacker/tp-link-v3-usb#11]
I followed each and every step but when I run command sudo make after some it show me error

/home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>

full description of error is below (Please help)

(kali㉿kali)-[~/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master]
└─$ sudo make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-kali3-amd64/build M=/home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-kali3-amd64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-11 (Debian 11.2.0-14) 11.2.0
  You are using:           gcc-11 (Debian 11.2.0-13) 11.2.0
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_cmd.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_security.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_debug.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_io.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_ioctl_query.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_ioctl_set.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_ieee80211.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_mlme.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_mlme_ext.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_mi.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_wlan_util.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_vht.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_pwrctrl.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_rf.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_recv.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_sta_mgt.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_ap.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/mesh/rtw_mesh.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_xmit.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_p2p.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_rson.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_tdls.o
  CC [M]  /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_br_ext.o
**/home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~**
compilation terminated.
make[2]: *** [/usr/src/linux-headers-5.15.0-kali3-common/scripts/Makefile.build:282: /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master/core/rtw_br_ext.o] Error 1
make[1]: *** [/usr/src/linux-headers-5.15.0-kali3-common/Makefile:1892: /home/kali/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-kali3-amd64'
make: *** [Makefile:2059: modules] Error 2

**Comment by keralahacker** [comment]
- [ ]  sudo apt update
- [ ]  sudo apt dist-upgrade
- [ ]  reboot

then follow the command below 

> sudo apt install linux-headers-$(uname -r)
> sudo apt install bc
> sudo rmmod r8188eu.ko
> sudo git clone https://github.com/keralahacker/tp-link-v3-usb
> cd tp-link-v3-usb
> sudo unzip realtek-rtl8188eus-keralahacker.zip
> cd realtek-rtl8188eus-dkms-kali-master
> sudo -i
> echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf"
> exit
> sudo make
> sudo make install
> sudo modprobe 8188eu
>
