### ISSUE TITLE
Unable to create Fake AP with TP-Link tl-wn722n v3 

### ISSUE THREAD

**Issue by zebdev786** [keralahacker/tp-link-v3-usb#2]

**Comment by keralahacker** [comment]
@zebdev786 can you explain which method you used to create Facke AP

**Comment by zebdev786** [comment]
> @zebdev786 can you explain which method you used to create Facke AP

Bascically I want to use fluxion but got MITM it won't work, please help me out, i'll be so much thankful to you.
