### ISSUE TITLE
sudo rmmod r8188eu.ko error

### ISSUE THREAD

**Issue by dollahsenju** [keralahacker/tp-link-v3-usb#3]
why error 
this is a command
sudo rmmod r8188eu.ko                                                              1 ⨯
rmmod: ERROR: Module r8188eu is not currently loaded

help me

**Comment by keralahacker** [comment]
Important note:

If after restarting your kali machine doesn't recognise your device.. As lot of people are facing the same problem .. I have a solution for you.. Whenever you restart your kali OS Insert the adapter and run the command

sudo rmmod r8188eu.ko

sudo modprobe 8188eu

Disconnect the device and connect again..
