### ISSUE TITLE
Error : Module r8188eu is not currently loaded

### ISSUE THREAD

**Issue by sabithchungam** [keralahacker/tp-link-v3-usb#6]
![16330695987044370590163458095046](https://user-images.githubusercontent.com/81108014/135575366-70c5dae6-3acf-4d65-b990-a3f0714c04db.jpg)

**Comment by keralahacker** [comment]
Important note:

If after restarting your kali machine doesn't recognise your device.. As lot of people are facing the same problem .. I have a solution for you.. Whenever you restart your kali OS Insert the adapter and run the command

sudo rmmod r8188eu.ko

sudo modprobe 8188eu

Disconnect the device and connect again..
