### ISSUE TITLE
problem in TP-link v3

### ISSUE THREAD

**Issue by ghnia** [keralahacker/tp-link-v3-usb#7]
hello sir : 
please help me in this regard. It will mean alot.
after I type the command below , u can see the screenshots 
![20211114_083554](https://user-images.githubusercontent.com/94271325/141666553-29915720-4b9f-4972-8739-65aa6c6934fc.jpg)

that happens everytime
![20211114_083532](https://user-images.githubusercontent.com/94271325/141666549-cd918bda-72a1-4a15-97e6-b8c720a6fd6c.jpg)

**sudo apt install linux-headers-$(uname -r)**

**Comment by keralahacker** [comment]
you have to manually run the below command

`sudo dpkg --configure -a`
