### ISSUE TITLE
Point of issue 

### ISSUE THREAD

**Issue by BAD-DOG-605** [keralahacker/tp-link-v3-usb#8]
┌──(kali㉿kali)-[~/tp-link-v3-usb]
└─$ cd realtek-rtl8188eus-dkms-kali-master        
                                                                                  
┌──(kali㉿kali)-[~/tp-link-v3-usb/realtek-rtl8188eus-dkms-kali-master]
└─$ sudo -i                                       
**┏━(Message from Kali developers)**
┃
┃ We have kept /usr/bin/python pointing to Python 2 for backwards
┃ compatibility. Learn how to change this and avoid this message:
┃ ⇒ https://www.kali.org/docs/general-use/python3-transition/
┃
┗━(Run: “touch ~/.hushlogin” to hide this message)
┌──(root💀kali)-[~]
└─# ^[[200~echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf"~
zsh: bad pattern: ^[[200~echo

**Comment by keralahacker** [comment]
the command that should copy and past in the sudo -i is given below 

`echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf"`
